SCRUM-214 : User Table Id 수정
Coordikitty/coordikitty-BE pull request #13
Opened 2024-07-25 05:58 UTC by hotteok00

## 개요
- User table PK 변경 및 코드 수정
## 작업사항
### 1. coordikitty-develop schema 수정 전 백업
- coordikitty-develop schema 백업
- coordikitty-deploy schema 생성
- coordikitty-deploy에 백업 본 업로드
### 2. User Record 삭제
- "jmg@naver.com" record 제외, 나머지 모두 삭제
- 이를 위해 삭제하고자 하는 record를 참조하는 record 삭제
  - 1. history, attach, postImage
  - 2. cloth, post
  - 3. user
### 3. User table Pk 변경
- binary(16) type의 id column 생성
- 기존 PK email에서 새로 생성한 id column으로 PK 변경
### 4. User table PK 변경으로인한 영향을 코드 전체에 반영
- 도메인 별로 수정작업 진행
- 간단한 테스트들은 통과했지만,
- **검수 필요**
## 기타
- firebase 내 레거시 파일은 삭제 못 함
- coordikitty-develop / coordikitty-deploy 구분 필요하다면 구분하는게 좋을 듯
- application.yml의 기존 raw api key 들을 intelliJ 환경변수로 변경

2024-07-25 09:32 UTC, Tentennball requested changes
변경사항 검토바랍니당

2024-07-25 09:32 UTC, Tentennball commented on src/main/java/Coordinate/coordikittyBE/domain/auth/withdraw/service/WithdrawService.java
아마 유저 삭제할떄 cascade해둬서 cloth, history, follow, post 다 자동으로 삭제되지 싶어요 파이어베이스 로직은 필요할 것 같고 유저만 삭제해주면 될듯!
->파이어베이스 로직 실행시키고-> 유저삭제

2024-07-25 09:32 UTC, Tentennball commented on src/main/java/Coordinate/coordikittyBE/domain/closet/controller/ClosetController.java
>      @DeleteMapping(value = "")
이건 제생각인데 pathVariable로 처리하면 어떨까 싶긴 함 /:clothId로(프론트랑 소통은 해야할듯)

2024-07-25 09:32 UTC, Tentennball commented on src/main/java/Coordinate/coordikittyBE/domain/post/posting/service/PostingService.java
attatch 지우고 다시 생성보다는 해당 postId로 attach를 찾고 그 안에있는 clothtIds를 업데이트 시키는건 어떨까 하는 생각입니다

2024-07-25 09:32 UTC, Tentennball commented on src/main/java/Coordinate/coordikittyBE/domain/post/postlike/service/PostlikeService.java
> +        historyRepository.save(history); // 필요없지 않나요?
필요없는거 맞음요!! 대신 함수위에 트랜잭션 어노테이션 붙여주세요ㅜㅜ(리팩토링하다 깜빡한듯)

2024-07-25 09:32 UTC, Tentennball commented on src/main/java/Coordinate/coordikittyBE/domain/post/postlike/service/PostlikeService.java
> +        if (history.getIsLiked()) post.like();
toogleLike 넣어놨는데 여기 두줄 추가해둔 이유가..?

2024-07-25 09:32 UTC, Tentennball commented on src/main/java/Coordinate/coordikittyBE/domain/recommend/service/RecommendService.java
> +//                .collect(Collectors.toList()); 필요 하나요?
빼도됨요~!!

2024-07-25 10:36 UTC, hotteok00 commented on src/main/java/Coordinate/coordikittyBE/domain/auth/withdraw/service/WithdrawService.java
저도 캐스캐이딩 되는 줄 알고 유저부터 삭제 했더니, 안된다고 디비에서 막더라구요.
찾아보니깐 참조 중인 테이블이 있으면 삭제가 안된다고 합니다. 물런 참조 무결성을 지키기 위한 제약 조건을 테이블에서 삭제하면, 레코드도 삭제가 가능한데 캐스캐이딩이 또 안되더라고요.
디비는 더 공부해보아야 할 것 같아요

2024-07-25 10:36 UTC, hotteok00 commented on src/main/java/Coordinate/coordikittyBE/domain/closet/controller/ClosetController.java
>      @DeleteMapping(value = "")
좋은 생각인거 같습니다. 주말 sprint에서 프론트랑 얘기 나눠봐요

2024-07-25 10:38 UTC, hotteok00 commented on src/main/java/Coordinate/coordikittyBE/domain/post/postlike/service/PostlikeService.java
> +        historyRepository.save(history); // 필요없지 않나요?
클래스에 @Transactional 붙어 있어서 함수에 추가로 붙일 필요는 없을 것 같아용

2024-07-25 10:38 UTC, hotteok00 commented on src/main/java/Coordinate/coordikittyBE/domain/recommend/service/RecommendService.java
> +//                .collect(Collectors.toList()); 필요 하나요?
확인.

2024-07-25 10:39 UTC, hotteok00 commented on src/main/java/Coordinate/coordikittyBE/domain/post/postlike/service/PostlikeService.java
> +        if (history.getIsLiked()) post.like();
toogleLike를 사용해야겠네요. 발견 못하고 지나친 부분 같습니다.

2024-07-25 10:40 UTC, hotteok00 commented
금요일에 이어서 코멘트 반영하도록 하겠습니다.

2024-07-26 00:33 UTC, hotteok00 commented on src/main/java/Coordinate/coordikittyBE/domain/post/postlike/service/PostlikeService.java
> +        if (history.getIsLiked()) post.like();
지금보니 toogleLike는 histroy 토글을 변경하는 메소드이고,
해당 로직에서 필요한 건 post의 좋아요 수 변경이기 때문에, toogleLike를 사용할 순 없습니다.

2024-07-26 01:04 UTC, hotteok00 commented on src/main/java/Coordinate/coordikittyBE/domain/post/posting/service/PostingService.java
코드를 다시 읽어보니, 애초에 postId는 해당 로직 상에서 불변하지 않나요? 그냥 postImage만 수정되고 끝나는 것 같은데요?
만약 그렇다면, post.update(postUpdateRequestDto, attaches, postImages); 해당 로직도 attach는 제외하고 변경되어야 할 것 같습니다.

2024-07-26 13:13 UTC, Tentennball commented on src/main/java/Coordinate/coordikittyBE/domain/auth/withdraw/service/WithdrawService.java
sql 워크벤치 들어가서 유저테이블 확인해보니 왜인지는 모르겠지만 외래키 설정이 tag빼고 다 풀려있더라구요. 설정 수정하고 코드 수정하니까 되네욥!

2024-07-28 06:19 UTC, merged